/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        pixel: {
          black: '#0a0a12',
          dark: '#12121f',
          mid: '#1e1e32',
          border: '#3a3a5c',
          muted: '#8888aa',
          text: '#c8c8e0',
          white: '#f4f4ff',
          green: '#00ff88',
          'green-dark': '#00cc6a',
          cyan: '#00e5ff',
          'cyan-dark': '#00b8cc',
          pink: '#ff6b9d',
          'pink-dark': '#cc5580',
          purple: '#c084fc',
          'purple-dark': '#9966cc',
          yellow: '#ffd700',
          'yellow-dark': '#ccaa00',
          orange: '#ff9f43',
          'orange-dark': '#cc7f36',
          red: '#ff4757',
          'red-dark': '#cc3a47',
          blue: '#60a5fa',
          'blue-dark': '#4d84c8',
          // Legacy alias
          light: '#c8c8e0',
        },
        accent: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#00ff88',
          600: '#00cc6a',
          700: '#059669',
          800: '#047857',
          900: '#065f46',
        },
        gray: {
          950: '#0a0a12',
        },
      },
      fontFamily: {
        pixel: ['"Press Start 2P"', 'monospace'],
        sans: ['"Press Start 2P"', 'monospace'],
        mono: ['"Press Start 2P"', 'monospace'],
      },
      fontSize: {
        'pixel-xs': ['8px', { lineHeight: '1.6' }],
        'pixel-sm': ['10px', { lineHeight: '1.6' }],
        'pixel-base': ['12px', { lineHeight: '1.8' }],
        'pixel-lg': ['14px', { lineHeight: '1.8' }],
        'pixel-xl': ['16px', { lineHeight: '1.8' }],
        'pixel-2xl': ['20px', { lineHeight: '1.6' }],
      },
      spacing: {
        'pixel': '4px',
        'pixel-2': '8px',
        'pixel-3': '12px',
        'pixel-4': '16px',
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
      borderWidth: {
        'pixel': '3px',
        'pixel-sm': '2px',
      },
      screens: {
        'xs': '375px',
        'touch': { 'raw': '(hover: none)' },
        'pointer': { 'raw': '(hover: hover)' },
      },
      borderRadius: {
        'none': '0',
        'pixel': '0',
      },
      animation: {
        'pixel-blink': 'pixelBlink 0.5s steps(2) infinite',
        'pixel-bounce': 'pixelBounce 0.4s steps(4) infinite',
        'pixel-shake': 'pixelShake 0.2s steps(4)',
        'pixel-pop': 'pixelPop 0.3s steps(6)',
        'pixel-float': 'pixelFloat 2s steps(8) infinite',
        'pixel-pulse': 'pixelPulse 1.5s steps(4) infinite',
        'pixel-walk': 'pixelWalk 0.4s steps(4) infinite',
        'pixel-jump': 'pixelJump 0.5s steps(6)',
        'fade-in': 'pixelPop 0.2s steps(4)',
        'slide-up': 'pixelPop 0.2s steps(4)',
        'slide-down': 'pixelPop 0.2s steps(4)',
        'scale-in': 'pixelPop 0.15s steps(3)',
        'pulse-glow': 'pixelPulse 1.5s steps(4) infinite',
        'shimmer': 'pixelShimmer 1s steps(4) infinite',
        'float': 'pixelFloat 2s steps(8) infinite',
      },
      keyframes: {
        pixelBlink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        pixelBounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '25%': { transform: 'translateY(-4px)' },
          '50%': { transform: 'translateY(0)' },
          '75%': { transform: 'translateY(-2px)' },
        },
        pixelShake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-2px)' },
          '75%': { transform: 'translateX(2px)' },
        },
        pixelPop: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pixelFloat: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        pixelPulse: {
          '0%, 100%': { boxShadow: '0 0 10px #00ff88' },
          '50%': { boxShadow: '0 0 25px #00ff88, 0 0 40px #00ff88' },
        },
        pixelShimmer: {
          '0%': { opacity: '0.5' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0.5' },
        },
        pixelWalk: {
          '0%, 100%': { transform: 'translateX(0) rotate(0deg)' },
          '25%': { transform: 'translateX(2px) rotate(-5deg)' },
          '75%': { transform: 'translateX(-2px) rotate(5deg)' },
        },
        pixelJump: {
          '0%': { transform: 'translateY(0) scaleY(1)' },
          '20%': { transform: 'translateY(0) scaleY(0.8)' },
          '40%': { transform: 'translateY(-20px) scaleY(1.1)' },
          '60%': { transform: 'translateY(-20px) scaleY(1)' },
          '80%': { transform: 'translateY(0) scaleY(0.9)' },
          '100%': { transform: 'translateY(0) scaleY(1)' },
        },
      },
      boxShadow: {
        'pixel': '4px 4px 0 #0a0a12',
        'pixel-sm': '2px 2px 0 #0a0a12',
        'pixel-lg': '6px 6px 0 #0a0a12',
        'pixel-glow': '0 0 20px #00ff88',
        'pixel-glow-pink': '0 0 20px #ff6b9d',
        'pixel-glow-cyan': '0 0 20px #00e5ff',
        'pixel-inset': 'inset -3px -3px 0 #1e1e32',
        'glow-sm': '0 0 10px rgba(0, 255, 136, 0.3)',
        'glow': '0 0 20px rgba(0, 255, 136, 0.4)',
        'glow-lg': '0 0 40px rgba(0, 255, 136, 0.5)',
      },
      transitionTimingFunction: {
        'pixel': 'steps(4)',
        'pixel-fast': 'steps(2)',
        'pixel-slow': 'steps(8)',
      },
    },
  },
  plugins: [],
};
